-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE ChatBOC.NumBOC (
	IdNum INT NOT NULL,
	NumeroBOC INT NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
