CREATE DATABASE IF NOT EXISTS ChatBoc;

CREATE TABLE `NumBOC` (
  `IdNum` int NOT NULL AUTO_INCREMENT,
  `NumeroBOC` int NOT NULL,
  PRIMARY KEY (`IdNum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci