name: Scrapper diario

on: 
  schedule:
    - cron: '0 17 * * 1-5'


jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/scrapper:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Run container
      run: |
        docker run -d --name scrapper your-dockerhub-username/scrapper:latest
